[colors]

[colors.file_panes]
background = "Red" 
border = "LightMagenta" 
hover = "Magenta" 
selected_focus = "LightMagenta" 
selected_no_focus = "Magenta" 
text_default = "LightMagenta" 
text_selected = "Black" 

[colors.path_trail]
