[colors]

[colors.file_panes]
background = "black" 
border = "#c397d8" 
hover = "Magenta" 
selected_focus = "#c397d8" 
selected_no_focus = "#523c51" 
text_default = "#c397d8" 
text_selected = "#000000" 

[colors.path_trail]
background = "#000000" 
text_default = "#c397d8" 
text_hovered = "White" 

[colors.prompt_bar]
background = "#0a0000" 
text_default = "#c397d8" 
text_hovered = "#FFFFFF" 
text_prompt = "#FFFFFF" 
